### ISSUE TITLE
SourceMap problem?

### ISSUE THREAD

**Issue by kachkaev** [stacktracejs/error-stack-parser#29]
Hi,

Looks like one of my dependencies is using your library and I get a strange error in the browser console every time the page loads:

> Failed to parse SourceMap: http://example.com/error-stack-parser.min.js.map

I don't have to perform any actions in order for the error to appear.

Browser: Chrome 49.0.2623.8 (latest for OSX)
Framework: Meteor 1.3-rc.9

Strangely, the issue does apply to FF (though I don't know whether FF reads .map files or not).

What could this be caused by?

**Comment by eriwen** [comment]
Could you please describe how you're using `ErrorStackParser` or `StackTrace`? I'm surprised that `error-stack-parser.min.js.map` is even being fetched. By default internal calls are filtered out of Stack Traces.

It's possible that the source map we're generating is indeed invalid for some reason.

**Comment by kachkaev** [comment]
The error is no longer seen. Don't quite remember when it was gone, but it must be during one of the meteor updates. False alarm :–)
