### ISSUE TITLE
include TypeScript in the npm distribution

### ISSUE THREAD

**Issue by hartshorne** [stacktracejs/error-stack-parser#33]
error-stack-parser.d.ts is not included in package.json (see https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) and does not seem to be included at all in npm.

the https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/error-stack-parser/index.d.ts version is stale since https://github.com/stacktracejs/error-stack-parser/commit/d9eb56a2804d0e5c1f3bf26e067a09f094fdd0de, and it'd be great if the updated definitions were bundled with the standard distribution. thanks!

**Comment by eriwen** [comment]
This is now shipped with error stack parser as of v2.0.1! Thanks!
