### ISSUE TITLE
Fails to correctly parse a stack trace for a file that has spaces in the name.

### ISSUE THREAD

**Issue by ashleydavis** [stacktracejs/error-stack-parser#46]
Hi thanks for this library. It looks great all though I've had some problems getting off the starting block with it.

I've prepared an example project which shows that this library fails to parse a stack trace that has spaces in its name.

I've prepared a test project to show the problem: https://github.com/ashleydavis/stack-trace-example

## Expected Behavior

Should be able to parse a stack trace for a file with spaces in it's name.

## Current Behavior

The name of the file that throws the error is "my test script.js".

As you can see by the following screenshot the initial components of the file name (before the space) are stripped out:

![stack trace issue](https://user-images.githubusercontent.com/625126/51240378-4a76d980-19c7-11e9-9d44-63ad0860cc71.png)

## Steps to Reproduce (for bugs)

I've prepared an example repository:
https://github.com/ashleydavis/stack-trace-example

Clone the repo. Or download and unpack the repo.
Use `npm install` to install dependencies.
Use `npm start` to run the example project.

You will see the problem in the parsed stack trace that is printed to the console.

## Context

I was hoping to use your stack trace parser in my project, but I've been blocked from using it by this problem.

## Your Environment

* stacktrace.js version: 2.0.2
* Browser Name and version: Node.js v8.9.4
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: https://github.com/ashleydavis/stack-trace-example

## Possible Solution

Sorry, no idea.

**Comment by niftylettuce** [comment]
You can close this, latest NPM release has this fixed.

**Comment by modethirteen** [comment]
👍

**Comment by eriwen** [comment]
Thanks both. Closing.
