### ISSUE TITLE
Cannot install because missing package in npm registry

### ISSUE THREAD

**Issue by billmn** [stacktracejs/error-stack-parser#51]
Today seems that the package isn't available in the npm registry.

I have tried to run <code>npm i error-stack-parser</code> but it returns this error:

![Schermata 2020-02-12 alle 11 53 04](https://user-images.githubusercontent.com/779534/74328464-3fd77100-4d8e-11ea-8454-907c6f08ef39.png)

I have tried to open https://registry.npmjs.org/error-stack-parser and this is the result:

![Schermata 2020-02-12 alle 11 55 00](https://user-images.githubusercontent.com/779534/74328618-8a58ed80-4d8e-11ea-8b2b-44f3d6e8ca08.png)

Thoughts??

**Comment by oncletom** [comment]
Has anyone here reached out to npm? Sounds weird the tarball disappeared while the `2.0.6` version is stated as published.

**Comment by hmonglee** [comment]
Issue with nmjs server :
 - get from France https://registry.npmjs.org/error-stack-parser => 404
 - get from Germany https://registry.npmjs.org/error-stack-parser => 200

**Comment by oncletom** [comment]
Sounds like npm team is now aware of this issue: https://status.npmjs.org/incidents/lvgmcrfvrvsh

**Comment by tamer-badawy** [comment]
i have tried
`npm i error-stack-parser`
and got and error say "error-stack-parser@latest" not found 
change it to a version number and it worked
`npm i error-stack-parser@2.0.6`

**Comment by barden42** [comment]
Same here 
`error An unexpected error occurred: "https://registry.yarnpkg.com/error-stack-parser/-/error-stack-parser-2.0.3.tgz: Request failed \"404 Not Found\"".
`

**Comment by bmikaeli** [comment]
same here. With yarn or with npm

**Comment by thedark1233** [comment]
Same here , 

can't use Larave-mix which have dependencies as "friendly-errors-webpack-plugin"

404 Not Found - GET https://registry.npmjs.org/error-stack-parser
npm ERR! 404  'error-stack-parser@^2.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'friendly-errors-webpack-plugin'

**Comment by billmn** [comment]
@thedark1233 Same here, I was also trying to install laravel-mix but with no luck

**Comment by dmyers-mitel** [comment]
I'm also having this issue, using npm on Windows.

**Comment by billmn** [comment]
I think it is better to wait until npm solve the problem:
https://status.npmjs.org/incidents/lvgmcrfvrvsh

**Comment by xsdaniel** [comment]
> Issue with nmjs server :
> 
>     * get from France https://registry.npmjs.org/error-stack-parser => 404
> 
>     * get from Germany https://registry.npmjs.org/error-stack-parser => 200

Thanks for this. If using a VPN there is no 404.

**Comment by alexis-riot** [comment]
Same for me from France. Can't use `npm install`

**Comment by t-miller** [comment]
![image](https://user-images.githubusercontent.com/19845698/74369969-4b359700-4da4-11ea-9989-b9b80e7a3557.png)

npm is saying the issue has been resolved but I'm still getting a 404 on `https://registry.npmjs.org/error-stack-parser`

**Comment by teedot83** [comment]
Still happening here too.....

**Comment by gfernandez-me** [comment]
"resolved" but still

**Comment by teedot83** [comment]
I sent an email to NPM support.

**Comment by teedot83** [comment]
Still down ... still no response from NPM

**Comment by HDVinnie** [comment]
I also sent a email to NPM support and they said it was resolved yet I'm still getting:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-stack-parser/-/error-stack-parser-2.0.6.tgz
npm ERR! 404 
npm ERR! 404  'error-stack-parser@2.0.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-12T20_27_59_861Z-debug.log
```

**Comment by brookslyrette** [comment]
Seeing this as well. 

East coast of Canada and I see a 404 page for: https://registry.npmjs.org/error-stack-parser

**Comment by blown5pt0** [comment]
Guess my builds are not getting done today at this rate....

**Comment by HDVinnie** [comment]
The weird thing is though that I can visit https://registry.npmjs.org/error-stack-parser/-/error-stack-parser-2.0.6.tgz locally on my Mac and the file downloads fine.

**Comment by xsdaniel** [comment]
@blown5pt0 - did you try with a VPN in the meantime? It is not the ideal solution but you can get your build done by today.

**Comment by gfernandez-me** [comment]
> The weird thing is though that I can visit https://registry.npmjs.org/error-stack-parser/-/error-stack-parser-2.0.6.tgz locally on my Mac and the file downloads fine.

just you, lol
I can't see shit

**Comment by billmn** [comment]
@blown5pt0 @xsdaniel I've used my phone's hotspot 🤦‍♂️

**Comment by fongoid** [comment]
https://status.npmjs.org/incidents/00tlqc4fzj14 new NPM issue to do with specific packages with 'error' in their name

**Comment by eriwen** [comment]
Hey folks, I can reach all the artifacts here in the US as of right now. This does indeed seem like something with NPM's CDN or servers. 

This new issue https://status.npmjs.org/incidents/00tlqc4fzj14 definitely affects this project :p — stay tuned.

**Comment by t-miller** [comment]
Looks like the issue has been resolved, as I can now access the package

**Comment by HDVinnie** [comment]
confirmed it is now working
