### ISSUE TITLE
Cannot install with yarn

### ISSUE THREAD

**Issue by t-miller** [stacktracejs/error-stack-parser#52]
After also experiencing issue #51, I tried installing with yarn, but receive the following error

`error An unexpected error occurred: "https://registry.yarnpkg.com/error-stack-parser/-/error-stack-parser-2.0.2.tgz: Request failed \"404 Not Found\"".`

**Comment by xsdaniel** [comment]
Same problem here! There is for some reason a 404 when visiting the [yarn package url](https://registry.yarnpkg.com/error-stack-parser/).

**Comment by xsdaniel** [comment]
@t-miller - In the meantime, you can use a VPN to install the package. At this time a Germany location works.

**Comment by eriwen** [comment]
Note this new NPM incident here looks like the cause: https://status.npmjs.org/incidents/00tlqc4fzj14
