### ISSUE TITLE
2.1.0 - incorrect TypeScript exports resulting in TypeError

### ISSUE THREAD

**Issue by jan-molak** [stacktracejs/error-stack-parser#75]
Hi @eriwen and many thanks for your work on `error-stack-parser`!

It looks like v2.1.0 has introduced a bug in TypeScript exports, preventing consumers of `error-stack-parser` from using the library in the intended way.

If you have a look at line 18 in `error-stack-parser.d.ts` in [this diff](https://github.com/stacktracejs/error-stack-parser/compare/v2.0.7...v2.1.0#diff-4cca18169d8ca3240eb941bdc4b36cfc0c492cbfdca198862f85db32c986c468L18):

<img width="1156" alt="Screenshot 2022-06-06 at 00 06 20" src="https://user-images.githubusercontent.com/1089173/172074292-d3ab553e-81c9-409c-b46a-d8b884db9211.png">

Type definitions changed in v2.1.0 suggest one should import `ErrorStackParser` using the default export as follows:

```typescript
import ErrorStackParser from 'error-stack-parser';

ErrorStackParser.parse(...) // TypeError in 2.1.0
```
which is different from v2.0.7, where we'd import the module like this:
```typescript
import * as ErrorStackParser from 'error-stack-parser';

ErrorStackParser.parse(...)
```

However, the change doesn't seem to have been applied to the [associated JavaScript code](https://github.com/stacktracejs/error-stack-parser/blob/2f051dc7201d5341fff7fe3b740574a3b8f0e3fd/dist/error-stack-parser.js#L9), which still uses the more traditional `module.exports = ErrorStackParser` export.

This means that importing the default export, as per the type definitions, results in `undefined` and a `TypeError`:

```
TypeError: Cannot read properties of undefined (reading 'parse')
```

## Your Environment

* Package version: 2.1.0
* Browser name and version: Node 16.13.1
* OS version (desktop or mobile): macOS 12.4
* Link to your project:

## Possible Workaround

Ignore the type definitions and use a var require instead:

```typescript
const ErrorStackParser = require('error-stack-parser');
```

## Possible Solution

If possible, I'd suggest reverting the change to `error-stack-parser.d.ts`:

```diff
- export default ErrorStackParser;
+ export = ErrorStackParser;
```

Or, if you prefer to use default exports, the associated JavaScript code would need to change to use
```diff
+ module.exports.default = ErrorStackParser
- module.exports = ErrorStackParser
```

If using the default export, I'd also suggest bumping the major version number, since this change is not backwards compatible.

**Comment by eriwen** [comment]
Hi @jan-molak. Thanks for the report. 

What I'm going to do here is revert the change (done in afc0a4c34791ce7fd535589cf796c2714cfc3462) and use `export = ErrorStackParser;` for v2.1.1 and then transition to `export default ...` (updating the JS too) for 3.0.0. 

The motivation for this change was to fix https://github.com/stacktracejs/error-stack-parser/issues/45 — I'd prefer to support a single way to invoke `ErrorStackParser.parse()` for maximum compatibility. 

Does this work for you?

**Comment by jan-molak** [comment]
Sure, sounds great! Thanks for getting back to me so quickly 👍🏻

**Comment by AnyGong** [comment]
@eriwen `https://www.npmjs.com/ `The 2.1.2 version can be searched, but the 2.1.2 cannot be found when the `nexus` is installed and synchronized. Is there a faster and better solution?

**Comment by eriwen** [comment]
Ah, sorry about that @jan-molak. `error-stack-parser` v2.1.3 fixes both of these issues.

**Comment by jan-molak** [comment]
Hey @eriwen - apologies for being a pain, but it seems like v2.1.3 has fixed the issue with the `stackframe`, but re-introduced the issue with the default export.

in [v2.1.3, error-stack-parser.d.ts](https://github.com/stacktracejs/error-stack-parser/blob/v2.1.3/error-stack-parser.d.ts):

```diff
import StackFrame = require("stackframe");  // this is fine now

declare namespace ErrorStackParser {
    export type {StackFrame};
    /**
     * Given an Error object, extract the most information from it.
     *
     * @param {Error} error object
     * @return {Array} of StackFrames
     */
    export function parse(error: Error): StackFrame[];
}

- export default ErrorStackParser;
+ export = ErrorStackParser
```
