### ISSUE TITLE
No matching version found for stackframe@^1.3.0.  It was specified as a dependency of 'error-stack-parser'

### ISSUE THREAD

**Issue by laoriy** [stacktracejs/error-stack-parser#76]
## Your Environment

* Package version:
* Browser name and version:
* OS version (desktop or mobile):
* Link to your project:

**Comment by JennerChen** [comment]
same problem 
![image](https://user-images.githubusercontent.com/5472912/172082366-58fc7f71-22ef-4961-a292-71feea2d7207.png)

**Comment by Drinjs** [comment]
Since the dependency stackframe@1.3.0 that version 2.10 depends on has not been released, please switch back to version 2.0.7

**Comment by Kyoloro** [comment]
new StackFrame error

StackFrame is not a construct

think about require('stackframe') -> stackframe.default

<img width="416" alt="image" src="https://user-images.githubusercontent.com/13166060/172086696-ff94378e-5d36-48bd-9ee5-fc2fa5a18c8a.png">

**Comment by eriwen** [comment]
This is likely a CDN issue. Please use v2.1.2+ of `error-stack-parser` if you encounter `StackFrame is not a constructor`.

**Comment by vinayg-cp** [comment]
> 2.0.7

This worked for us, thank you.
